### ISSUE TITLE
README

### ISSUE THREAD

**Issue by dancinglightning** [jasontruluck/tmdb_rexx#5]
Hi, 
i just saw this lib posted on google and asking for feedback so here is some.
Great coverage and code climate! I like that kind of thing.

But, I was wondering why you would write a new library when there is four listed already. And i don't mean that in a bad way, really. Just  a question.
If you think of selling it, what would be it's strong points.
Or if you think of convincing me to use (and then quite likely contribute), why would i choose this one.

I'd suggest you put that in the readme, so it's not just for me.

Would also be nice to hear how you use it, possible an example.

**Comment by jasontruluck** [comment]
Hi! 

Sorry for the delayed response, the holidays have me busy. Thank you for the great compliments and interest! 

I hope you do not find my motivations dissatisfying, but it mainly started out of a desire to learn the API more throughly for a side project I was working on. After reviewing the Gems that existed at the time (I believe there were only 3 then? I may be mistaken about this) the available options were either not fitting what I needed (i.e. implemented endpoints), were (seemingly) unmaintained, or of a style that I did not really enjoy working with (i.e. Active Record style). While none of these things are absolutely cause for creating a new wrapper or bad in any way I figured I wanted to learn the API more throughly so why not?

The strong point I feel for this library are that it is meant to be as minimal as possible. I am trying to avoid doing any unnecessary processing on top of the responses from the API (i.e. object instantiation for the use as an interface) which was a motivation as well in removing `Hashie` from this library and returning straight JSON. That being said, I can not honestly say this is a better approach than any of the other libraries out there (they all look great as well), just my preferred implementation so that a user can control what they do with the JSON after the fact. I suppose I figure that I am not the only one wishing to have something of this style so why not make it and add it as a a possible option for other users?

Given all of this I have not added something to the README of this nature for the reason that I do not think there is anything compellingly different other than methodology and opinion (which I would love to discuss). I hope that this does not discourage you from trying the Gem or contributing to it if you use it, I just like to be frank about my motivations :smile:. 

Thank you for your feed back!

**Comment by dancinglightning** [comment]
Hi
thanks for the elaborate and honest answer. I think it's well worth putting this minimal approach into the readme. The pure json thing, it's a good thing to know for people who have to make choices.

I'll still give a spin, though i do like my objects. I just tried themoviedb-api and that looked to be working.
Also has good coverage, i do so like good coverage.
Speaking of themoviedb-api, check out their readme https://github.com/18Months/themoviedb-api
which goes a long way to make one want to use it.
I'll get back with a new issue if i have something, thanks
